---

- name: Пример подключения роли с параметрами
  hosts: webservers
  become: true
  gather_facts: true

  roles:
    - role: nginx_demo
      vars:
        nginx_port: 8080
      when: ansible_os_family == "Debian"
      tags: ['web', 'install']
