---
- name: Задачи с условиями
  hosts: all
  gather_facts: true
  vars:
    create_file: true

  tasks:
    - name: Установить Htop только в Ubuntu
      ansible.builtin.apt:
        name: htop
        state: present
      when: ansible_facts['distribution'] == "Ubuntu"

    - name: Создать файл если включен
      ansible.builtin.file:
        path: /tmp/test.txt
        state: touch
        mode: "0644"
      when: create_file

    - name: Проверить, существует ли файл
      ansible.builtin.stat:
        path: /tmp/test.txt
      register: file_info

    - name: Удалить файл если существует
      ansible.builtin.file:
        path: /tmp/test.txt
        state: absent
      when: file_info
