---

- name: Сборка Docker-образа приложения
  hosts: localhost
  become: true

  tasks:
    - name: Собрать образ из Dockerfile
      community.docker.docker_image:
        state: present
        name: myapp
        tag: v0.0.1
        force_source: true
        source: build
        build:
          path: ./app
          dockerfile: Dockerfile
          pull: true
