- name: Установка кастомного Nginx-контейнера
  hosts: db1
  become: true

  vars:
    app_env: production

  tasks:
    - name: Убедиться, что образ nginx загружен
      community.docker.docker_image:
        name: nginx
        source: pull

    - name: Скопировать конфиг nginx
      ansible.builtin.template:
        src: nginx.conf.j2
        dest: /tmp/nginx.conf
        mode: "0644"
      notify: Перезапустить nginx

    # - name: Удалить файл
    #   ansible.builtin.file:
    #     path: /tmp/nginx.conf
    #     state: absent

    - name: Запустить контейнер nginx
      community.docker.docker_container:
        name: nginx
        image: nginx
        state: started
        restart_policy: always
        ports:
          - "8080:80"
        volumes:
          - /tmp/nginx.conf:/etc/nginx/conf.d/default.conf:ro
        env:
          APP_ENV: "{{ app_env }}"

  handlers:
    - name: Перезапустить nginx
      community.docker.docker_container:
        name: nginx
        state: started
        restart: true
