---
- name: "Настройка веб-сервера"
  hosts: webservers
  become: true
  tasks:
    - name: "Установить nginx"
      ansible.builtin.apt:
        name: nginx
        state: present
        update_cache: true

    - name: "Создать стартовую страницу"
      ansible.builtin.copy:
        content: "<h1>Hello from Ansible</h1>"
        dest: /var/www/html/index.html
        mode: '0644'

    - name: "Убедиться, что nginx запущен"
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: true
