---
# tasks file for roles/nginx_demo
- name: Тестовая задача в роли nginx_demo
  ansible.builtin.debug:
    msg: "Роль nginx_demo работает!"
  tags: web

- name: Тестовая задача в роли nginx_demo
  ansible.builtin.debug:
    msg: "{{ nginx_port }}"
  tags: install
